### ISSUE TITLE
Add IVORY

### ISSUE THREAD

**Issue by kanthvallampati** [uhub/awesome-css#7]
https://github.com/kanthvallampati/IVORY was deprecated in the favour of https://github.com/IVORY-UI/ivory. Please add the new IVORY Framework - https://github.com/IVORY-UI/ivory in your list.

**Comment by ccding** [comment]
can you submit a pull request?

**Comment by kanthvallampati** [comment]
@ccding Created a pull request. Please review.

A suggestion - why don’t you categorize the curated list.

**Comment by ccding** [comment]
`A suggestion - why don’t you categorize the curated list.`

This list is generated by a script.
